### ISSUE TITLE
How would the constraint examples be done programmatically?

### ISSUE THREAD

**Issue by ewhite-dev** [MatejBalantic/MBAutoGrowingTextView#11]
How would the constraints from the examples be replicated programmatically?

My MBAutoGrowingTextView is inside of a scrollview and here is what I tried

//the horizontal positioning of the textView
     [_internalScrollView addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"H:|[_textView(scrollViewSize)]|"
                                                                     options:NSLayoutFormatDirectionLeadingToTrailing
                                                                     metrics:metrics
                                                                       views:elementDict]];

//a constraint I added that is intended to make the textview expand downward, instead of upward (was able to make this work in the example project with Interface Builder, but doesn't work in my app programmatically
            [_internalScrollView addConstraint:[NSLayoutConstraint
                                            constraintWithItem:_textView
                                            attribute:NSLayoutAttributeTop
                                            relatedBy:NSLayoutRelationEqual
                                            toItem:_internalScrollView
                                            attribute:NSLayoutAttributeTop
                                            multiplier:1.0f
                                            constant:1.0]];

//the three sizing constraints
        [_internalScrollView addConstraint:[NSLayoutConstraint constraintWithItem:_textView attribute:NSLayoutAttributeHeight relatedBy:NSLayoutRelationGreaterThanOrEqual toItem:nil attribute:NSLayoutAttributeNotAnAttribute multiplier:1.0 constant:33]];

```
    [_internalScrollView addConstraint:[NSLayoutConstraint constraintWithItem:_textView attribute:NSLayoutAttributeHeight relatedBy:NSLayoutRelationEqual toItem:nil attribute:NSLayoutAttributeNotAnAttribute multiplier:1.0 constant:33]];

    [_internalScrollView addConstraint:[NSLayoutConstraint constraintWithItem:_textView attribute:NSLayoutAttributeHeight relatedBy:NSLayoutRelationLessThanOrEqual toItem:nil attribute:NSLayoutAttributeNotAnAttribute multiplier:1.0 constant:200]];
```

**Comment by MatejBalantic** [comment]
This library is no longer maintained and is being archived.
