### ISSUE TITLE
Height should be optional when setting a min height

### ISSUE THREAD

**Issue by jshier** [MatejBalantic/MBAutoGrowingTextView#3]
Right now an assertion will fire if there's no NSLayoutRelationEqual relation on a height constraint, even if there's a NSLayoutRelationGreaterThanOrEqual relation in place. It seems unnecessary to have both, as the equal relation could be created on the fly. I was stuck for a little while until I realized that it was a requirement. At the very least it should be made clearer in the documentation, as explicit height constraints aren't always required for a fully constrained layout.

**Comment by MatejBalantic** [comment]
This library is no longer maintained and is being archived.
