### ISSUE TITLE
Infinite loop in layoutSubview

### ISSUE THREAD

**Issue by jshier** [MatejBalantic/MBAutoGrowingTextView#4]
As seems to be fairly common when subclassing UITextView on iOS 7.1, I'm hitting an infinite loop in layoutSubviews when using this pod with the view having scrolling enabled. With scrolling disabled it doesn't work to resize but otherwise doesn't cause an infinite loop.

**Comment by chriscdn** [comment]
I fixed this by disabling scrolling and calling `[textView setNeedsLayout]` on the textView delegate.

**Comment by kakali** [comment]
Like chadkouse, I've implemented my own sizeThatFits method, it seems to work fine and doesn't crash but I also needed to add some lines to layoutSubviews to scroll the text to the end when it's expanding. No guarantee if it always displays fine though. Works for my case.

**Comment by kakali** [comment]
Check out the pull requests. There's dannofx's fix which seems to work nice, or mine.

**Comment by lastcc** [comment]
@pikaboo @jshier  Then don't call `[self sizeThatFits:self.frame.size];`

We can take advantage of the fact that UITextView's super class is UIScrollView: 

```swift
override var contentSize: CGSize {
        didSet {
            DispatchQueue.main.async {
                self.updateHeightConstraint()
            }
        }
    }

private func updateHeightConstraint() {
        var newHeight = contentSize.height
        
        newHeight = min(max(minHeight, newHeight), maxHeight)
        if newHeight != heightConstraint.constant {
            heightConstraint.constant = newHeight
        }
    }
```

**Comment by MatejBalantic** [comment]
This library is no longer maintained and is being archived.
