### ISSUE TITLE
Is there anyway we can use this without storyboard?

### ISSUE THREAD

**Issue by RyanNelwan** [MatejBalantic/MBAutoGrowingTextView#6]
Our project literally does not use storyboard. Is there a way we can use this library without it?

Thanks.

**Comment by kakali** [comment]
It's possible, with small modifications. If you init the textbox from code and not from a nib file, you'll start with no constraints. You have to add them manually and then call associateConstraints manually (e.g. in runtime by performSelector, or simply add the method to the MBAutogrowingTextView.h file). The textbox will work fine.

**Comment by kakali** [comment]
Check out my pull request. In the first commit I've added better support for from-code initialization along with a demo.

**Comment by alperkayabasi** [comment]
@kakali Thank you, simply calling associateConstraints() after settings constraints programmatically does the trick. No need for anything else.

**Comment by MatejBalantic** [comment]
This library is no longer maintained and is being archived.
