### ISSUE TITLE
 self.constraints is nil in iOS 8

### ISSUE THREAD

**Issue by taitanxiami** [MatejBalantic/MBAutoGrowingTextView#7]
if self.constraints is nil, wo can't get heightConstraint.

**Comment by kakali** [comment]
If you init the textbox from code and not from a nib file, you'll start with no constraints. You have to add them manually and then call associateConstraints manually (e.g. in runtime by performSelector, or simply add the method to the MBAutogrowingTextView.h file)

**Comment by karthisiva** [comment]
@LargeShrimp same issues i am facing, did you find out solution?

**Comment by MatejBalantic** [comment]
This library is no longer maintained and is being archived.
