### ISSUE TITLE
Application stop responding

### ISSUE THREAD

**Issue by hassanraza-maavratech** [MatejBalantic/MBAutoGrowingTextView#8]
If return key is pressed 2 times .. Whole application stop responding

**Comment by Pacek** [comment]
+1 it's stuck in layoutSubviews method

**Comment by kakali** [comment]
It's the fault of calling sizeThatFits. I've overriden the sizeThatFits method and now it seems to work fine (doesn't crash, but I haven't tested if my calculations don't spoil expanding in some cases. It grows fine for me though). However, why sizeThatFits actually calls layoutSubviews, is a mystery to me. Probably Apple's bug?

**Comment by kakali** [comment]
Check out issue #4 (Infinite loop in layoutSubview).

**Comment by MatejBalantic** [comment]
This library is no longer maintained and is being archived.
